# Generated by Django 2.2.12 on 2020-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_hod_other_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Other Name'),
        ),
    ]
